config/routes.rb
Rails.application.routes.draw do
  root 'drivers#index'

  resources :drivers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/driver.rb
class Driver < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
    def index
        @drivers = Driver.all
    end

    def new
        @driver = Driver.new
    end

    def create
        @driver = Driver.create(driver_params)
        if @driver.valid?
          redirect_to root_path
        else
          render :new, status: :unprocessable_entity
        end
    end

    private

    def driver_params
      params.require(:driver).permit(:name, :address, :license_no)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
    def index
      end
    end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/drivers/index.html.erb
<div class="title">
    <div class="row feature text-center">
        <div class="col-12 col-sm">
          <h1>Hitch A Ride With Us!</h1>
    </div>
</div>

app/views/drivers/new.html.erb
<br />

<div class="booyah-box col-10 offset-1">
  <h1>Sign Up to Drive</h1>
  <br />
   <%= simple_form_for @driver do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :license_no %>
    <br />
    <%= f.submit 'Register', class: 'btn btn-primary' %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rideshare</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="navbar navbar-toggleable-md navbar-inverse bg-inverse">
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
        <%= link_to 'Rideshare', root_path, class: 'navbar-brand' %>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
        <ul class="navbar-nav mr-auto mt-2 mt-md-0">
          <li class="nav-item active">
             <%= link_to new_driver_path, class: 'nav-link' do %>
               <i class="fa fa-plus-circle"></i>
               Join the Team
             <% end %>
          </li>

          <li class="nav-item active">
            <a class="nav-link" href="#">Call A Ride <span class="sr-only">(current)</span></a>
          </li>
        </ul>
      </div>
        
    </nav>
    <%= yield %>
  </body>
</html>

app/views/layouts/drivers/new.html.erb
<div class="booyah-box col-10 offset-1">
  <h1>Sign Up to Drive</h1>
   <%= simple_form_for @driver do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :license_no %>
    <br />
    <%= f.submit 'Register', class: 'btn btn-primary' %>
  <% end %>
</div>